### ISSUE TITLE
updateFieldsAndIndexes errors

### ISSUE THREAD

**Issue by markpfletcher** [perfectsense/dari#87]
When starting a brightspot instance we are seeing multiple errors of the form:-

Jun 22, 2015 1:26:31 PM com.psddev.dari.db.ObjectType updateFieldsAndIndexes
WARNING: Can't use [class java.lang.Class] for [genericType] in [com.wearefriday.domain.taxonomy.Tag]!
Jun 22, 2015 1:26:31 PM com.psddev.dari.db.ObjectType updateFieldsAndIndexes
WARNING: Can't use [class com.wearefriday.persistence.EditorialContentDAO] for [editorialContentDAO] in [com.wearefriday.domain.CustomLocation]!

Can you please advise the cause of the error and how to fix?

**Comment by Ryan-Anderson** [comment]
Dari expects all fields in your class to be serializable to the db. The above warning indicates that `genericType` can't be used as a field, because it is not serializable. If you do not need this field saved to the database, you may want to mark this field as `transient`. Otherwise, if you need a serializable field, you may want to consider using `ObjectType` instead of `Class`.

**Comment by Ryan-Anderson** [comment]
Resolving this issue. Let us know if you have any additional questions.
